---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.zncdata.dev
  resources:
  - authenticationclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - superset.zncdata.dev
  resources:
  - supersetclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - superset.zncdata.dev
  resources:
  - supersetclusters/finalizers
  verbs:
  - update
- apiGroups:
  - superset.zncdata.dev
  resources:
  - supersetclusters/status
  verbs:
  - get
  - patch
  - update
