# permissions for end users to view supersetclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: supersetcluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: superset-operator
    app.kubernetes.io/part-of: superset-operator
    app.kubernetes.io/managed-by: kustomize
  name: supersetcluster-viewer-role
rules:
- apiGroups:
  - superset.zncdata.dev
  resources:
  - supersetclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - superset.zncdata.dev
  resources:
  - supersetclusters/status
  verbs:
  - get
